DarenTechs.Web/Controllers/ApplicationRoleController.cs
using DarenTechs.Data.Identity;
using DarenTechs.Web.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace DarenTechs.Web.Controllers
{
    public class ApplicationRoleController : Controller
    {
        private readonly RoleManager<IdentityRole> roleManager;
        private readonly UserManager<ApplicationUser> userManager;

        public ApplicationRoleController(RoleManager<IdentityRole> roleManager, UserManager<ApplicationUser> userManager)
        {
            this.roleManager = roleManager;
            this.userManager = userManager;
        }

        [HttpGet]
        public IActionResult Index()
        {
            var model = new List<ApplicationRoleListViewModel>();
            foreach (var role in roleManager.Roles)
            {
                model.Add(new ApplicationRoleListViewModel
                {
                    RoleName = role.Name,
                    NumberOfUsers = userManager.Users.Where(u => userManager.IsInRoleAsync(u, role.Name).Result).Count(),
                    Id = role.Id
                });
            }

            return View(model);
        }
        [HttpGet]
        public async Task<IActionResult> AddEditApplicationRole(string id)
        {
            ApplicationRoleViewModel model = new ApplicationRoleViewModel();
            if (!String.IsNullOrEmpty(id))
            {
                IdentityRole applicationRole = await roleManager.FindByIdAsync(id);
                if (applicationRole != null)
                {
                    model.Id = applicationRole.Id;
                    model.RoleName = applicationRole.Name;
                }
            }
            return PartialView("_AddEditApplicationRole", model);
        }
        [HttpPost]
        public async Task<IActionResult> AddEditApplicationRole(string id, ApplicationRoleViewModel model)
        {
            if (ModelState.IsValid)
            {
                bool isExist = !String.IsNullOrEmpty(id);
                IdentityRole applicationRole = isExist ? await roleManager.FindByIdAsync(id) :
               new IdentityRole();
                applicationRole.Name = model.RoleName;
                IdentityResult roleRuslt = isExist ? await roleManager.UpdateAsync(applicationRole)
                                                    : await roleManager.CreateAsync(applicationRole);
                if (roleRuslt.Succeeded)
                {
                    return RedirectToAction("Index");
                }
            }
            return View(model);
        }

        [HttpGet]
        public async Task<IActionResult> DeleteApplicationRole(string id)
        {
            string name = string.Empty;
            if (!String.IsNullOrEmpty(id))
            {
                IdentityRole applicationRole = await roleManager.FindByIdAsync(id);
                if (applicationRole != null)
                {
                    name = applicationRole.Name;
                }
            }
            return PartialView("_DeleteApplicationRole", name);
        }

        [HttpPost]
        public async Task<IActionResult> DeleteApplicationRole(string id, IFormCollection form)
        {
            if (!String.IsNullOrEmpty(id))
            {
                IdentityRole applicationRole = await roleManager.FindByIdAsync(id);
                if (applicationRole != null)
                {
                    IdentityResult roleRuslt = roleManager.DeleteAsync(applicationRole).Result;
                    if (roleRuslt.Succeeded)
                    {
                        return RedirectToAction("Index");
                    }
                }
            }
            return View();
        }
    }
}

DarenTechs.Web/Controllers/BlogAdminController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using DarenTechs.Data.Data;
using DarenTechs.Data.Entities.Blog;
using DarenTechs.Data.Interfaces;
using DarenTechs.UI.Components.Modal;
using DarenTechs.Blog.ViewModels;
using DarenTechs.Web.Services;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace DarenTechs.Web.Controllers
{
    public class BlogAdminController : Controller
    {
        private IBlogService _service;

        public BlogAdminController(IBlogService service)
        {
            _service = service;
        }

        public ActionResult Index() => View(_service.GetLatestBlog());

        [HttpGet]
        public ActionResult BlogPagedPublishedList(int page, int pageSize, bool isPublished) 
            => PartialView("_BlogAdminPosts", _service.BlogPagedPublishedList(page, pageSize, isPublished));


        // GET: BlogAdmin/Create
        [HttpGet]
        public ActionResult Designer()
        {
            return View();
        }

        [HttpGet]
        public IActionResult AddParagraph([ModelBinder(BinderType = typeof(BootstrapModalBinder))] BootstrapModal bootstrapmodal) 
            => PartialView("_ParagraphModal", bootstrapmodal);
        
    }
}

DarenTechs.Web/Controllers/BlogController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using DarenTechs.Data.Data;
using DarenTechs.Data.Entities.Blog;
using DarenTechs.Data.Interfaces;
using DarenTechs.Blog.ViewModels;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace DarenTechs.Web.Controllers
{
    public class BlogController : Controller
    {

        private IRepository<Post> _repository;

        public BlogController(IRepository<Post> repository)
        {
            _repository = repository;
        }

        // GET: Blog
        public ActionResult Index()
        {
            var post = new BlogViewModel(_repository.GetAll().OrderByDescending(o => o).FirstOrDefault());

            return View(post);
        }

        [Route("Blog/Navigation/{id:long}")]
        public ActionResult Navigation(long id)
        {
            var post = new BlogViewModel(_repository.GetById(id));

            return View("Index",post);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult AddComment(BlogCommentViewModel blogcomment)
        {
            if (ModelState.IsValid)
            {
                var comments = new List<Comment>();

                var comment = new Comment
                {
                    Body = blogcomment.Body
                };

                comments.Add(comment);

                var post = new Post
                {
                    Id = blogcomment.PostId,
                    Comments = comments
                };

                _repository.Update(post);
                return View("Index", post);
            }

            return View("Index");
        }

       
    }
}

DarenTechs.Web/Controllers/UserController.cs
using DarenTechs.Data.Identity;
using DarenTechs.Web.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace DarenTechs.Web.Controllers
{
    public class UserController : Controller
    {
        private readonly UserManager<ApplicationUser> userManager;
        private readonly RoleManager<IdentityRole> roleManager;

        public UserController(UserManager<ApplicationUser> userManager, RoleManager<IdentityRole> roleManager)
        {
            this.userManager = userManager;
            this.roleManager = roleManager;
        }

        [HttpGet]
        public IActionResult Index()
        {
            List<UserListViewModel> model = new List<UserListViewModel>();
            model = userManager.Users.Select(u => new UserListViewModel
            {
                Id = u.Id,
                Name = u.UserName,
                Email = u.Email
            }).ToList();
            return View(model);
        }

        [HttpGet]
        public IActionResult AddUser()
        {
            UserViewModel model = new UserViewModel();
            model.ApplicationRoles = roleManager.Roles.Select(r => new SelectListItem
            {
                Text = r.Name,
                Value = r.Id
            }).ToList();
            return PartialView("_AddUser", model);
        }

        [HttpPost]
        public async Task<IActionResult> AddUser(UserViewModel model)
        {
            if (ModelState.IsValid)
            {
                ApplicationUser user = new ApplicationUser
                {
                    UserName = model.UserName,
                    Email = model.Email
                };
                IdentityResult result = await userManager.CreateAsync(user, model.Password);
                if (result.Succeeded)
                {
                    IdentityRole applicationRole = await roleManager.FindByIdAsync(model.ApplicationRoleId);
                    if (applicationRole != null)
                    {
                        IdentityResult roleResult = await userManager.AddToRoleAsync(user, applicationRole.Name);
                        if (roleResult.Succeeded)
                        {
                            return RedirectToAction("Index");
                        }
                    }
                }
            }
            return View(model);
        }

        [HttpGet]
        public async Task<IActionResult> EditUser(string id)
        {
            EditUserViewModel model = new EditUserViewModel();
            model.ApplicationRoles = roleManager.Roles.Select(r => new SelectListItem
            {
                Text = r.Name,
                Value = r.Id
            }).ToList();

            if (!String.IsNullOrEmpty(id))
            {
                ApplicationUser user = await userManager.FindByIdAsync(id);
                if (user != null)
                {
                    model.Name = user.UserName;
                    model.Email = user.Email;
                    //model.ApplicationRoleId = roleManager.Roles.Single(r => r.Name == userManager.GetRolesAsync(user).Result.Single()).Id;
                    model.UserRoles = await userManager.GetRolesAsync(user);
                    //model.ApplicationRoleId = roleManager.Roles.SingleOrDefault(r => r.Name == model.UserRoles[0])?.Id;
                }
            }
            return PartialView("_EditUser", model);
        }

        [HttpPost]
        public async Task<IActionResult> AddUserToRole([FromForm]string id, [FromForm]string applicationRoleId)
        {
            if (!String.IsNullOrEmpty(applicationRoleId) && !string.IsNullOrEmpty(id))
            {
                //IdentityRole role = await roleManager.FindByNameAsync(role);
                var user = await userManager.FindByIdAsync(id);
                var role = await roleManager.FindByIdAsync(applicationRoleId);
                if (user != null)
                {
                    await userManager.AddToRoleAsync(user, role.Name);
                }
            }
            return RedirectToAction("index");
        }

        [HttpPost]
        public async Task<IActionResult> EditUser(string id, EditUserViewModel model)
        {
            if (ModelState.IsValid)
            {
                ApplicationUser user = await userManager.FindByIdAsync(id);
                if (user != null)
                {
                    //user.Name = model.Name;
                    user.Email = model.Email;
                    string existingRole = userManager.GetRolesAsync(user).Result.Single();
                    string existingRoleId = roleManager.Roles.Single(r => r.Name == existingRole).Id;
                    IdentityResult result = await userManager.UpdateAsync(user);
                    if (result.Succeeded)
                    {
                        if (existingRoleId != model.ApplicationRoleId)
                        {
                            IdentityResult roleResult = await userManager.RemoveFromRoleAsync(user, existingRole);
                            if (roleResult.Succeeded)
                            {
                                IdentityRole applicationRole = await roleManager.FindByIdAsync(model.ApplicationRoleId);
                                if (applicationRole != null)
                                {
                                    IdentityResult newRoleResult = await userManager.AddToRoleAsync(user, applicationRole.Name);
                                    if (newRoleResult.Succeeded)
                                    {
                                        return RedirectToAction("Index");
                                    }
                                }
                            }
                        }
                    }
                }
            }
            return PartialView("_EditUser", model);
        }

        [HttpGet]
        public async Task<IActionResult> DeleteUser(string id)
        {
            string name = string.Empty;
            if (!String.IsNullOrEmpty(id))
            {
                ApplicationUser applicationUser = await userManager.FindByIdAsync(id);
                if (applicationUser != null)
                {
                    name = applicationUser.UserName;
                }
            }
            return PartialView("_DeleteUser", name);
        }

        [HttpPost]
        public async Task<IActionResult> DeleteUser(string id, IFormCollection form)
        {
            if (!String.IsNullOrEmpty(id))
            {
                ApplicationUser applicationUser = await userManager.FindByIdAsync(id);
                if (applicationUser != null)
                {
                    IdentityResult result = await userManager.DeleteAsync(applicationUser);
                    if (result.Succeeded)
                    {
                        return RedirectToAction("Index");
                    }
                }
            }
            return View();
        }
        [HttpGet]
        public async Task<IActionResult> DeleteUserRole(string username, string role)
        {
            string name = string.Empty;
            var vm = new UserRoleViewModel();
            if (!String.IsNullOrEmpty(role) && !string.IsNullOrEmpty(username))
            {
                //IdentityRole role = await roleManager.FindByNameAsync(role);
                var user = await userManager.FindByNameAsync(username);
                if (role != null)
                {
                    //vm.RoleId = role.Id;
                    vm.RoleName = role;//.Name;
                    vm.UserId = user.Id;
                }
            }
            return PartialView("_DeleteUserRole", vm);
        }

        [HttpPost]
        public async Task<IActionResult> DeleteUserRoleFinish([FromForm]string userId, [FromForm]string roleName)
        {
            if (!String.IsNullOrEmpty(roleName) && !string.IsNullOrEmpty(userId))
            {
                //IdentityRole role = await roleManager.FindByNameAsync(role);
                var user = await userManager.FindByIdAsync(userId);
                if (user != null)
                {
                    await userManager.RemoveFromRoleAsync(user, roleName);
                }
            }
            return View("Index");

            //return PartialView("_DeleteUserRole", vm);
        }
    }
}

DarenTechs.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="description" content="A Site of technical knowledge and fun" />
    <meta name="keywords" content="Asp.net Core" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - DarenTechs WebSite</title>

    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />


</head>
<body>
    <div class="container-fluid" id="logo_banner">
        <div class="row">
            <div id="logo">
                <div id="logo_text">
                    <h1><a href="/home">Daren<span class="logo_colour">Techs</span></a></h1>
                    <h2>A place for learning and interest.</h2>
                </div>
            </div>
        </div>
    </div>

    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#topnavbar" aria-controls="topnavbar" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="topnavbar">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                    <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                </li>



                <environment include="Development">
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Blog</a>
                        <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <li class="nav-item"><a class="nav-link" asp-area="" asp-controller="Blog" asp-action="Index">Main Blog</a></li>
                            <li class="nav-item"><a class="nav-link" asp-area="" asp-controller="BlogAdmin" asp-action="Index">Blog Aministration</a></li>
                            <li class="nav-item"><a class="nav-link" asp-area="" asp-controller="BlogAdmin" asp-action="Designer">Blog Creator</a></li>
                        </ul>
                    </li>
                </environment>
                <environment exclude="Development">
                    @if (User.IsInRole("Administrator"))
                    {
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Blog</a>
                            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <li class="nav-item"><a class="nav-link" asp-area="" asp-controller="Blog" asp-action="Index">Main Blog</a></li>
                                <li class="nav-item"><a class="nav-link" asp-area="" asp-controller="BlogCreator" asp-action="Index">Blog Creator</a></li>
                            </ul>
                        </li>
                    }
                    else
                    {
                        <li class="nav-item"><a class="nav-link" asp-area="" asp-controller="Blog" asp-action="Index">Blog</a></li>
                    }
                </environment>
                <li class="nav-item"><a class="nav-link" asp-area="" asp-controller="Home" asp-action="About">About</a></li>
                <li class="nav-item"><a class="nav-link" asp-area="" asp-controller="Home" asp-action="Contact">Contact</a></li>
                <environment include="Development">
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Administrator</a>
                        <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <li class="nav-item"><a class="nav-link" asp-area="" asp-controller="ApplicationRole" asp-action="Index">Role</a></li>
                            <li class="nav-item"><a class="nav-link" asp-area="" asp-controller="User" asp-action="Index">User</a></li>
                        </ul>
                    </li>
                </environment>
                <environment exclude="Development">
                    @if (User.IsInRole("Administrator"))
                    {
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Administrator</a>
                            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <li class="nav-item"><a class="nav-link" asp-area="" asp-controller="ApplicationRole" asp-action="Index">Role</a></li>
                                <li class="nav-item"><a class="nav-link" asp-area="" asp-controller="User" asp-action="Index">User</a></li>
                            </ul>
                        </li>
                    }
                </environment>

            </ul>
            <form class="form-inline my-2 my-lg-0">
                <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
                <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
            </form>
            @await Html.PartialAsync("_LoginPartial")
        </div>
    </nav>

    @RenderBody()

    <script src="~/lib/jquery/dist/jquery.js"></script>
    <script src="~/lib/popper/dist/popper.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
    <script src="~/js/knockout-3.4.2.js" asp-append-version="true"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/js/jquery.bootpag.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>